name: king-co
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - google-auth
  - earthengine-api
  - cachetools
  - geopandas
  - georaster
  - ipyleaflet
  - pandas-gbq
  - whitebox
  - folium
  - rasterio
  - altair
